# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
prediction_ranbu <- function(nodes1, y_base, nodes2, h) {
    .Call(`_dirf_prediction_ranbu`, nodes1, y_base, nodes2, h)
}

#' @export
stl_sort <- function(x) {
    .Call(`_dirf_stl_sort`, x)
}

#' @export
quantile_dnrb_aux <- function(quantis, y_unique, y, weights) {
    .Call(`_dirf_quantile_dnrb_aux`, quantis, y_unique, y, weights)
}

#' @export
quantile_dnrb <- function(quantis, y_unique, y, nodes1, nodes2, h) {
    .Call(`_dirf_quantile_dnrb`, quantis, y_unique, y, nodes1, nodes2, h)
}

